image: docker:stable

services:
  - docker:dind

stages:
 - build:minimal
 - build:default
 - build:dreamshell
 - release

variables:
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: ""

before_script:
 - docker info
 - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN hub.nold.in

build_minimal:
 stage: build:minimal
 variables:
  RELEASE_TAG: minimal
  RELEASE_IMAGE: hub.nold.in/$CI_PROJECT_PATH:$RELEASE_TAG
 script:
  - docker build -t $RELEASE_IMAGE minimal/
  - docker push $RELEASE_IMAGE

build_default:
 stage: build:default
 variables:
  RELEASE_TAG: latest
  RELEASE_IMAGE: hub.nold.in/$CI_PROJECT_PATH:$RELEASE_TAG
 script:
  - docker build -t $RELEASE_IMAGE default/
  - docker push $RELEASE_IMAGE

build_dreamshell:
 stage: build:dreamshell
 variables:
  RELEASE_TAG: dreamshell
  RELEASE_IMAGE: hub.nold.in/$CI_PROJECT_PATH:$RELEASE_TAG
 script:
  - docker build -t $RELEASE_IMAGE dreamshell/
  - docker push $RELEASE_IMAGE
