image: docker:stable

services:
  - docker:dind

stages:
 - build_minimal
 - build_default
 - build_dreamshell
 - release

variables:
  DOCKER_DRIVER: overlay

before_script:
 - docker info
 - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN hub.nold.in

build_minimal:
 stage: build
 variables:
  RELEASE_TAG: minimal
  RELEASE_IMAGE: hub.nold.in/$CI_PROJECT_PATH:$RELEASE_TAG
 script:
  - docker build -t $RELEASE_IMAGE minimal/Dockerfile
  - docker push $RELEASE_IMAGE

build_default:
 stage: build
 variables:
  RELEASE_TAG: latest
  RELEASE_IMAGE: hub.nold.in/$CI_PROJECT_PATH:$RELEASE_TAG
 script:
  - docker build -t $RELEASE_IMAGE default/Dockerfile
  - docker push $RELEASE_IMAGE

build_dreamshell:
 stage: build
 variables:
  RELEASE_TAG: dreamshell
  RELEASE_IMAGE: hub.nold.in/$CI_PROJECT_PATH:$RELEASE_TAG
 script:
  - docker build -t $RELEASE_IMAGE dreamshell/Dockerfile
  - docker push $RELEASE_IMAGE
